packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  cpu-features: set this to true or false
  esbuild: true
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  ssh2: set this to true or false
storeDir: C:/Code/.pnpm
